# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'd09' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for d09
#	pod 'ibohun2020', :path => '/Users/ibohun/Downloads/ibohun2020'
#	pod 'ibohun2020', :path => '/Users/ivan/Downloads/ibohun2020'
	pod 'ibohun2020', :path => '/Users/ibohun/Swift/ibohun2020'
	

end
